### ISSUE TITLE
Could you please add an open-source license to use the code for `EpiFilter`?

### ISSUE THREAD

**Issue by ntmv** [kpzoo/EpiFilter#3]
@kpzoo thank you for making the code for `EpiFilter` publicly available! Would it be possible to add an open source license to the repo? Our team is very interested in looking at the performance of `EpiFilter` on our data, and as of now without a license we cannot use your code ([Information about opensource license](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)). Thanks!

**Comment by kpzoo** [comment]
Thanks, I think the license is added now. Hope EpiFilter helps!

**Comment by ntmv** [comment]
Thank you so much!
